### ISSUE TITLE
Would it be possible to add iOS 17?

### ISSUE THREAD

**Issue by alpennec** [kishikawakatsumi/applelocalization-web#128]
I'm curious to know why iOS 17 is not available. Would it be possible to add this version too?
Thanks!

**Comment by pan93412** [comment]
Related: https://github.com/kishikawakatsumi/applelocalization-data/issues/34

**Comment by kishikawakatsumi** [comment]
To add, I don't want to do this until the next version comes out because there is still a possibility of an update.
