### ISSUE TITLE
License terms of the translations

### ISSUE THREAD

**Issue by jordimas** [kishikawakatsumi/applelocalization-web#66]
It will be good to add in the web page what are the licensing terms of the glossary translations (technically own by apple). Thanks

**Comment by kishikawakatsumi** [comment]
@jordimas Thank you for the suggestion. It is a very good idea. If possible, could you provide a good example of how it would be appropriate to write? I am not familiar with this part of the document and I am afraid I might write something wrong.

**Comment by kishikawakatsumi** [comment]
Perhaps there is a misunderstanding. I do not have a licence for these files. I am doing this without permission.
